/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author i7 MAX GAMER
 */
public class EditarPerfil extends javax.swing.JFrame {

    /**
     * Creates new form EditarPerfil
     */
    public EditarPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        TFCedulaEditarPerfil = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        TFNombreEditarPerfil = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        TFApellifoEditarPerfil = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        TFCallePrinEditarPerfil = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        TFCalleSecuEditarPerfil = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        TFTelefonoEditarPerfil = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        TFEmailEditarPerfil = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        TFNickNameEditarPerfil = new javax.swing.JTextField();
        enterEditarPerfil = new javax.swing.JButton();
        TFPasswordEditarPerfil = new javax.swing.JPasswordField();
        jLabel58 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_User_96px_Verde.png"))); // NOI18N
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel36.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(62, 150, 148));
        jLabel36.setText("Cedula: ");
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 106, -1, -1));
        jPanel5.add(TFCedulaEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 90, -1));

        jLabel40.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(62, 150, 148));
        jLabel40.setText("Nombre: ");
        jPanel5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel5.add(TFNombreEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 90, -1));

        jLabel41.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(62, 150, 148));
        jLabel41.setText("Apellido: ");
        jPanel5.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel5.add(TFApellifoEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 90, -1));

        jLabel42.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(62, 150, 148));
        jLabel42.setText("Calle Pricipal: ");
        jPanel5.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, 20));
        jPanel5.add(TFCallePrinEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 130, -1));

        jLabel52.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(62, 150, 148));
        jLabel52.setText("Calle Secundaria: ");
        jPanel5.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, 20));
        jPanel5.add(TFCalleSecuEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 130, -1));

        jLabel53.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(62, 150, 148));
        jLabel53.setText("Telefono: ");
        jPanel5.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, 20));
        jPanel5.add(TFTelefonoEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 90, -1));

        jLabel54.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(238, 112, 82));
        jLabel54.setText("Calle Pricipal: ");
        jPanel5.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, 20));
        jPanel5.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 130, -1));

        jLabel55.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(62, 150, 148));
        jLabel55.setText("Email: ");
        jPanel5.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));
        jPanel5.add(TFEmailEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 130, -1));

        jLabel56.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(62, 150, 148));
        jLabel56.setText("NickName: ");
        jPanel5.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel57.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(62, 150, 148));
        jLabel57.setText("Password: ");
        jPanel5.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        jPanel5.add(TFNickNameEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 90, -1));

        enterEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Enter_OFF_v.png"))); // NOI18N
        enterEditarPerfil.setBorderPainted(false);
        enterEditarPerfil.setContentAreaFilled(false);
        enterEditarPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterEditarPerfil.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Enter_ON_v.png"))); // NOI18N
        enterEditarPerfil.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Enter_ON_v.png"))); // NOI18N
        enterEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterEditarPerfilActionPerformed(evt);
            }
        });
        jPanel5.add(enterEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 110, 30));
        jPanel5.add(TFPasswordEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 90, -1));
        jPanel5.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterEditarPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterEditarPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFApellifoEditarPerfil;
    private javax.swing.JTextField TFCallePrinEditarPerfil;
    private javax.swing.JTextField TFCalleSecuEditarPerfil;
    private javax.swing.JTextField TFCedulaEditarPerfil;
    private javax.swing.JTextField TFEmailEditarPerfil;
    private javax.swing.JTextField TFNickNameEditarPerfil;
    private javax.swing.JTextField TFNombreEditarPerfil;
    private javax.swing.JPasswordField TFPasswordEditarPerfil;
    private javax.swing.JTextField TFTelefonoEditarPerfil;
    private javax.swing.JButton enterEditarPerfil;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
